# tasks file for group
---
- name: Add IAM group
  hosts: localhost
  tasks:
  - name: Create Two Groups, Devops and Luigi
    community.aws.iam:
      iam_type: group
      name: "{{ item }}"
      state: present
    loop:
     - Devops
     - Luigi
    register: new_groups